### ISSUE TITLE
运行xgboost算法出错

### ISSUE THREAD

**Issue by shazi4399** [FudanMPL/Garnet#31]
你好，我在尝试运行Garnet框架。

我在clone后，按照「SecureML协议使用」案例步骤进行了测试。在这一步还可以顺利执行得到预期的结果。

但是，在执行「运行XGBoost模型安全训练」案例步骤时，发生了问题。

具体来说，在执行[运行XGBoost模型安全训练](https://github.com/FudanMPL/Garnet#%E8%BF%90%E8%A1%8C)步骤时，Python脚本报错。
```Python
python ./compile.py xgboost -R 32
```

错误信息如下：
```shell
(base) zhanghao@thinkcentre:~/Downloads/mycode/Garnet$ python ./compile.py xgboost -R 32
Default bit length: 31
Default security parameter: 40
(93, 1, 0, 0)
Compiling file /home/zhanghao/Downloads/mycode/Garnet/Programs/Source/xgboost.mpc
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
WARNING: Order of memory instructions not preserved, errors possible
Writing to /home/zhanghao/Downloads/mycode/Garnet/Programs/Bytecode/xgboost-multithread-1.bc
Traceback (most recent call last):
  File "/home/zhanghao/Downloads/mycode/Garnet/./compile.py", line 41, in <module>
    main(compiler)
  File "/home/zhanghao/Downloads/mycode/Garnet/./compile.py", line 36, in main
    compilation(compiler)
  File "/home/zhanghao/Downloads/mycode/Garnet/./compile.py", line 19, in compilation
    prog = compiler.compile_file()
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/compilerLib.py", line 383, in compile_file
    exec(compile(infile.read(), infile.name, "exec"), self.VARS)
  File "/home/zhanghao/Downloads/mycode/Garnet/Programs/Source/xgboost.mpc", line 24, in <module>
    trainer.fit()
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/xgboost.py", line 160, in fit
    tree.fit()
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/xgboost.py", line 462, in fit
    self.train_layer(k)
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/xgboost.py", line 418, in train_layer
    self.TrainInternalNodes(k, self.x, self.y, self.y_pred, self.g, self.NID)
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/xgboost.py", line 413, in TrainInternalNodes
    AID, Threshold = self.GlobalTestSelection(x, y, y_pred, g)
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/xgboost.py", line 389, in GlobalTestSelection
    def _(j):
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/library.py", line 1034, in decorator
    def f(i):
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/library.py", line 930, in decorator
    range_loop(loop_body, start, stop, step)
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/library.py", line 894, in range_loop
    while_loop(loop_fn, condition, start, g=loop_body.__globals__)
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/library.py", line 1449, in while_loop
    if_statement(pre_condition, lambda: do_while(loop_fn, g=g))
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/library.py", line 1596, in if_statement
    if_fn()
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/library.py", line 1449, in <lambda>
    if_statement(pre_condition, lambda: do_while(loop_fn, g=g))
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/library.py", line 1523, in do_while
    condition = _run_and_link(loop_fn, g)
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/library.py", line 1490, in _run_and_link
    res = function()
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/library.py", line 1443, in loop_fn
    result = loop_body(arg)
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/library.py", line 882, in loop_fn
    res = loop_body(i)
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/library.py", line 1040, in f
    state = reducer(tuplify(loop_body(j)), state)
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/xgboost.py", line 394, in _
    t[j][:], s[j][:] = self.AttributeWiseTestSelection(
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/xgboost.py", line 374, in AttributeWiseTestSelection
    s, t = GroupMax(gg, s, t)
  File "/home/zhanghao/Downloads/mycode/Garnet/Compiler/group_ops.py", line 68, in GroupMax
    if debug:
NameError: name 'debug' is not defined
```

请问这个问题有什么方法可以解决吗

**Comment by GuopengLin** [comment]
如果有其他问题，欢迎及时联系

**Comment by shazi4399** [comment]
谢谢问题已解决！
